### ISSUE TITLE
links to gitorious

### ISSUE THREAD

**Issue by harry-wood** [osmrmhv/osmrmhv#2]
The site links to gitorious for the source code https://gitorious.org/osmrmhv but that's saying "no projects found"   so maybe this github repo is the new home? in which case we need to [fix links](https://github.com/osmrmhv/osmrmhv/search?utf8=✓&q=gitorious&type=)

**Comment by johnfreed** [comment]
Apparently this is indeed the new home. From what you posted earlier, Harry Wood, I discovered the correct Gitorious link:

https://gitorious.org/osmrmhv/lib
