### ISSUE TITLE
Server may have tripped up?

### ISSUE THREAD

**Issue by leighghunt** [osmrmhv/osmrmhv#6]
Hi,

Thanks for this great tool, which I frequently use when trying to figure out what's going on with OSM edits - looks like the service may have stopped recently, as a job I just submitted is in position 4039 in the queue? (http://osmhv.openstreetmap.de/changeset.jsp?id=63180669)

Cheers,
Leigh

**Comment by cdauth** [comment]
I restarted the service

**Comment by pangoSE** [comment]
It is still not working. This is queue no1: http://osmrm.openstreetmap.de/relation.jsp?id=371743 I waited the whole evening and still no1.
Same with http://osmhv.openstreetmap.de/blame.jsp?id=371743 no 158 as of writing.
This webapp seems broken to me.

**Comment by cdauth** [comment]
Well the problem is that this relation is so huge that it probably takes days to download all the necessary data from the OSM API. Trying to analyze relations so huge is what makes the service get stuck in the first place.

**Comment by leighghunt** [comment]
Mines at position 2 now, so it's getting there! :-)
