### ISSUE TITLE
https://osmhv.openstreetmap.de is down

### ISSUE THREAD

**Issue by don-vip** [osmrmhv/osmrmhv#7]
Not sure if this is the right place to report it, but https://osmhv.openstreetmap.de/ is down (reported from https://josm.openstreetmap.de/ticket/17621)

**Comment by mmd-osm** [comment]
Pinging @Nakaner, @giggls, as openstreetmap.de is owned by FOSSGIS e.V.

**Comment by giggls** [comment]
People are responsible for their services themselves. Usually we do not even know how their startup works.

**Comment by cdauth** [comment]
The problem is that the setup was lost, and I don't have a backup. The service is written in JSP, and it seems like no one is using that anymore. I tried setting up winstone as before but couldn't get it to run, then I tried Tomcat and also failed. If someone knows how to get a JSP app running nowadays and can share the setup with me, I can put the service back online.

**Comment by giggls** [comment]
Is this a war file? If so I can install jetty for you.

**Comment by cdauth** [comment]
It is a war file, but I'm not sure it's working the way it's supposed to. In the last 3 commits I tried modifying the way the war file was built, but without success. If you could install jetty, that would be great, then I can try once more to get it to run.

**Comment by giggls** [comment]
OK, please contact me by mail to talk about server configuration stuff.

**Comment by Loomie** [comment]
> If someone knows how to get a JSP app running nowadays and can share the setup with me, I can put the service back online.

@cdauth: JSP apps can be run for example with [Tomcat](http://tomcat.apache.org/whichversion.html) or [Jetty](https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html).

1. I have build the project with Maven (`mvn package`). The resulting file `target/osmhv-SNAPSHOT.war` is used.
2. [Download Tomcat 8.5](https://tomcat.apache.org/download-80.cgi) and extract it. Make sure Java is available. Run it with `startup.sh` and check `yourserver:8080` that it is running.
3. Stop Tomcat (`shutdown.sh`) and deploy your web app. Just copy the WAR to the folder `webapps` below the Tomcat installation.
4. Start Tomcat and see your web app running under `http://yourserver:8080/osmhv-SNAPSHOT/`.

> It is a war file, but I'm not sure it's working the way it's supposed to.

So I can confirm that the code is still working with a recent version of Tomcat. For a production setup the configuration has to be adapted.

**Comment by cdauth** [comment]
It should be working again now, please test

**Comment by don-vip** [comment]
It seems to work but it's very slow. I don't remember if the site was faster before. Maybe it needs to index/cache osm changeset data?

**Comment by cdauth** [comment]
For some reason Tomcat is keeping the connection open for 20 seconds for each static JS/CSS file after it is transmitted, so the browser is waiting for that before showing the page...

**Comment by cdauth** [comment]
I set up Jetty now, is it better?
